Develop
CyberCoHuK/java-filmorate pull request #22
Opened 2023-06-13 12:01 UTC by CyberCoHuK

Third iteration

2023-06-13 18:31 UTC, Frilock requested changes
Добрый день, укажите пожалуйста в файле Readme те задачи которые вы выбрали.

2023-06-14 12:43 UTC, Frilock requested changes
Добрый день, поздравляю с первой большой совместной работой. Надеюсь было интересно и вам понравилось командное взаимодействие. По работе, в целом, написанные вами запросы к БД мне понравились, все было хорошо "сджойнено", по ним претензий особо нет. В целом я оставил ряд комментариев, но они все довольно маленькие и в большей части касаются форматирования кода и мест где можно сделать лучше. Хотя есть и ошибки.
В некоторых местах я оставил вопросы, и если вы с чем то не согласны то можете мне на них ответить и я при следующем ревью посмотрю еще раз.
Успехов

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    Long timestamp;
Отсутствуют приватные модификаторы

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public String toString() {
Вроде данный toString стандартный его можно заменить на аннотацию от Lombok, но это в качестве предложения

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      Set<Integer> friendsList = new HashSet<>();
Вообще хочется, чтобы все ваши объекты модели имели один вид в части работы с модификаторами доступа. Где то вы используете @FieldDefaults(level = AccessLevel.PRIVATE), а где то нет, лично мне больше нравиться стандартный подход с использованием модификатора. Давайте сделаем однотипно.

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public Director createDirector(Director director) {
Честно говоря не очень понятен подход, зачем делать 2 запроса если можно ограничиться одним. Пускай метод directorStorage.createDirector(director) отдает сразу объект, а не идентификатор. А то получается вы сначала создали объект, а потом зачем то идете его искать. Это ведь лишние затраты

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        directorStorage.updateDirector(director);
Аналогично. То есть не очень понятна ваша логика. Может вы ее объясните мне и я с вами соглашусь

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            case "director":
Предлагаю тут использовать enum тоже, это даст дополнительную валидацию данных. Кроме того, предлагаю каждый запрос внутри case вынести в отдельный метод, чтобы сам метод не был бы таким "громоздким"

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (genreId == 9999 && year == 9999) {
Вот я как сторонний наблюдатель вообще не понимаю что это за числа и почему они такие? Как минимум число нужно вынести в приватную константу класса, чтоб по названию было понятно что оно обозначает.
Кроме того, а почему именно такое ограничение?

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmService.searchFilmByParameter(query.toLowerCase(), filmSearchParameter.toLowerCase());
А тут у вас NPE случиться не может? Вроде параметр у вас не обязательный.

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                throw new NullPointerException("Задан не корректный параметр сортировки");
Кидать исключение NullPointer не верно, кидайте либо свое "кастомное" либо IllegalArgument...

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +
Следуя вашей логике - лишний пробел

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        log.info("Получить список директоров");
Лог если честно не очень корректный, вы напишите тогда что ли - выполняем получения списка директоров, а лучше еще возвращать сколько записей было найдено

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        isExist(id);
Название метода не очень нравится, directorExistById, или как то так. Вроде так лучше?)

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            final String sqlCheck = "SELECT * FROM film_genre  WHERE film_id = ? AND genre_id = ?";
Лишний пробел добавляете

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +
Лишняя пустая строка

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return null;
Обычно когда у метода класса нет какой то реализации принято бросать внутри исключение UnsoportedOperation...как то так =)
Чтобы в случае чего вы сразу поняли что вызываете не ту реализацию

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(FIRST_FILM_DATE)) {
Тут кроме того, надо бы по идее проверять что дата не null

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/DirectorMapper.java
> +        return new Director(rs.getInt("id"),
Вроде в 1 строку влезает

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/DirectorMapper.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
А для чего тут эта аннотация?

2023-06-14 12:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/EventMapper.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Разве тут нужна аннотация?

2023-06-14 12:43 UTC, Frilock commented on src/main/resources/schema.sql
> +    content     varchar    NOT NULL,
Когда создаете строковые поля, вам нужно продумать их размерность, потому что где то стандартного размера хватит, а где наоборот будет много/мало

2023-06-14 12:43 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        filmStorage.addLike(film2.getId(), user.getId());
Числовые префиксы и окончания для названия локальных/глобальных переменных не особо приветствуются, лучше именовать как то по другому, например, user, friendUser - что угодно

2023-06-14 13:55 UTC, CyberCoHuK commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/DirectorMapper.java
> +        return new Director(rs.getInt("id"),
Влезала. Но я еще сменил на билдер чтоб было однотипно для всех.

2023-06-14 14:51 UTC, CyberCoHuK commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                if (!directorRows.next()) {
Как раз есть задания со звездочкой. Может уже там реализуем =)

2023-06-14 15:05 UTC, CyberCoHuK commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(FIRST_FILM_DATE)) {
Данный метод уже устарел по идеи. Теперь это проверяется на уровне валидации (как и в целом старая реализация) которую некоторые вроде советуют даже удалять.  У даты есть @NotNull и @BeginOfCinemaEra

2023-06-14 18:58 UTC, ArturKaralis commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmService.searchFilmByParameter(query.toLowerCase(), filmSearchParameter.toLowerCase());
параметр изменен на обязательный, NPE исключен валидацией обязательного поля

2023-06-15 15:05 UTC, Frilock requested changes
Добрый день, в целом молодцы, есть пара мелких моментов в части опечаток и неверного типа логирования. Поправьте, пожалуйста, и я приму работу

2023-06-15 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    Long timestamp;
Лично мне нравиться больше просто использование модификатора private =)

2023-06-15 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                throw new IllegalArgumentException("Задан не корректный параметр сортировки");
Еще бы не мешало добавить какой конкретно не корректный параметр =)

2023-06-15 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        log.warn("Директор с идентификатором {} отправлен.", id);
А почему лог warn? Произошла какая то нештатная ситуация разве?

2023-06-15 16:00 UTC, ArturKaralis commented on src/main/java/ru/yandex/practicum/filmorate/enums/SortTypesForDirectors.java
> +    UNKNOW("");
Добавлено описание

2023-06-15 16:35 UTC, ArturKaralis commented
А вдруг коммент поможет? ^_^

2023-06-15 16:54 UTC, ArturKaralis approved these changes
done

2023-06-16 12:41 UTC, Frilock approved these changes
Молодцы, принято

2023-06-16 16:31 UTC, merged