first iteration
CyberCoHuK/java-filmorate pull request #3
Opened 2023-04-11 15:57 UTC by CyberCoHuK

2023-04-12 16:39 UTC, Frilock requested changes
Добрый день, отсутствуют unit тесты на Ваш код.

2023-04-12 16:39 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Должны присутствовать unit тесты:
Добавлены тесты для валидации. Есть тесты на на граничных условиях

2023-04-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) user.setName(user.getLogin());
Чтобы не делать 2 таких проверки можно подключить библиотеку от apache common 3, и использовать StringUtils.isBlank(...)
В данной библиотеке довольно много полезных функций

2023-04-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    @PutMapping()
Пустые скобки не нужны

2023-04-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final HashMap<Integer, User> users = new HashMap<>();
По code style данная константа располагается выше чем обычные приватные поля

2023-04-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private int userId = 1;
А разве идентификатор не должен быть статичным?

2023-04-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            throw new ValidationException();
Сюда не нужно описание ошибки добавить?)

2023-04-13 14:25 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе

2023-04-13 14:25 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void validate(@Valid @RequestBody Film film) {
@Valid @RequestBody тут не нужны, Вы же этот метод вызываете из других методов контроллера

2023-04-13 14:25 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new ValidationException("Такой фильм уже существует");
Такой, это какой? Нужно в лог какой то признак добавить

2023-04-13 14:25 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (StringUtils.isEmpty(user.getName())) user.setName(user.getLogin());
Большая просьба обособлять if,else,for и т.д. даже если они из 1й строчки состоят

2023-04-13 18:37 UTC, Frilock requested changes
Еще пара мелочей

2023-04-13 18:37 UTC, Frilock commented on pom.xml
> +        <org.apache.commons.version>3.12.0</org.apache.commons.version>
org по идее можно не писать

2023-04-13 18:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(FIRSTFILMDATE)) {
FIRST_FILM_DATE в таком виде пишутся константы, вроде уже обсуждали этот момент.
Кроме того, я вроде написал, а может ли быть что film.getReleaseDate null вернет?

2023-04-13 19:12 UTC, CyberCoHuK commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(FIRSTFILMDATE)) {
По идеи не вернёт. Валидация notnull

2023-04-14 15:41 UTC, Frilock approved these changes
Принял. Если что, то в гитхабе можно отвечать на комментарии (где с чем то не согласны) или "закрывать", которые поправили.

2023-04-14 15:45 UTC, merged