First iteration add-database
CyberCoHuK/java-filmorate pull request #5
Opened 2023-05-19 09:07 UTC by CyberCoHuK

2023-05-19 19:19 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе.

2023-05-19 19:19 UTC, Frilock commented on pom.xml
> +            <version>5.2.5.Final</version>
Давайте версию вынесем в properties, чтобы изменение версий происходило более удобно

2023-05-19 19:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +@Slf4j
Логгер добавлен, но не используется

2023-05-19 19:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +public class MpaService {
Вообще добавленные в данной работе сервисы и хранилища имеют одинаковую структуру, в таком случае можно сделать базовый абстрактный класс, с основной логикой, а в добавленных сервисах только наследоваться от него. 
На ваше усмотрение

2023-05-19 19:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                .releaseDate(rs.getDate("release_date").toLocalDate())
а release_date null не может быть?

2023-05-19 19:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Mpa makeMpa(ResultSet rs, int rowNum) throws SQLException {
Предложил бы данные методы вынести в отдельный класс маппер (можно даже и не в один), чтобы разделить логику запросов к БД и маппинга

2023-05-19 19:19 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +        film = Film.builder()
Чтобы не "захламлять" метод setUp предложил бы создание объектов вынести в отдельные приватные методы, чтобы было как то так: film = createFilm();

2023-05-19 19:19 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +    Film film;
К полям необходимо добавить модификаторы приватные, кроме того, использование числовых префиксов и окончаний не приветствуется.

2023-05-19 20:30 UTC, CyberCoHuK commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                .releaseDate(rs.getDate("release_date").toLocalDate())
Внутри таблицы not null и в классе фильмов валидатор.

2023-05-20 09:10 UTC, CyberCoHuK commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +public class MpaService {
Тут я уже не осилил чет :) Может потом попробую сменить как осмыслю

2023-05-20 17:42 UTC, Frilock requested changes
Добрый вечер, в мапперах отсутствуют модификаторы, кроме того предлагаю их сделать бинами.

2023-05-20 17:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/FilmMapper.java
> +    JdbcTemplate jdbcTemplate;
А куда модификаторы пропали?)
Кроме того, Вы эти маперы можете сделать бинами (навесив аннотацию компонент), и также инжектить где Вам нужно

2023-05-20 18:15 UTC, CyberCoHuK commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/FilmMapper.java
> +    JdbcTemplate jdbcTemplate;
Ничего не понял из написанного :)

2023-05-21 15:53 UTC, Frilock requested changes
Добрый день, немножко не так меня поняли, комментарий оставил, если что пишите.

2023-05-21 15:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/UserMapper.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Зачем это?)

2023-05-21 15:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/UserMapper.java
> +@Component("userMapper")
В скобках можно и не писать ничего, там где Вам нужен UserMapper вы его и инжектите, где FilmMapper то там инжектите его

2023-05-21 15:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> -    private final UserMapper userMapper;
Было правильно

2023-05-22 15:38 UTC, Frilock approved these changes
Принято

2023-05-23 06:56 UTC, merged